#! /bin/bash

output=$(~/.waypoints/adg.py ${@})

if [[ ! $1 ]] || [[ ${1} == "-h" ]]
then 
~/.waypoints/adg.py -h
elif [[ "$output" ]] && [[ ${@} = "-l" ]]
then
~/.waypoints/adg.py -l
elif [[ "$output" ]]
then
cd $output
fi


    

